"""Módulo con la enumeración de colores."""

from enum import StrEnum


class Colors(StrEnum):
    """
    Enumeración de nombres de colores utilizados en la aplicación.

    Esta clase define varias constantes de colores para elementos de la interfaz.
    """

    ALICE_BLUE = "alice blue"
    ANTIQUE_WHITE = "antique white"
    AQUA = "aqua"
    AQUAMARINE = "aquamarine"
    AZURE = "azure"
    BEIGE = "beige"
    BISQUE = "bisque"
    BLACK = "black"
    BLANCHED_ALMOND = "blanched almond"
    BLUE = "blue"
    BLUE_VIOLET = "blue violet"
    BROWN = "brown"
    BURLYWOOD = "burlywood"
    CADET_BLUE = "cadet blue"
    CHARTREUSE = "chartreuse"
    CHOCOLATE = "chocolate"
    CORAL = "coral"
    CORNFLOWER_BLUE = "cornflower blue"
    CORNSILK = "cornsilk"
    CRIMSON = "crimson"
    CYAN = "cyan"
    DARK_BLUE = "dark blue"
    DARK_CYAN = "dark cyan"
    DARK_GOLDENROD = "dark goldenrod"
    DARK_GRAY = "dark gray"
    DARK_GREEN = "dark green"
    DARK_KHAKI = "dark khaki"
    DARK_MAGENTA = "dark magenta"
    DARK_OLIVE_GREEN = "dark olive green"
    DARK_ORANGE = "dark orange"
    DARK_ORCHID = "dark orchid"
    DARK_RED = "dark red"
    DARK_SALMON = "dark salmon"
    DARK_SEA_GREEN = "dark sea green"
    DARK_SLATE_BLUE = "dark slate blue"
    DARK_SLATE_GRAY = "dark slate gray"
    DARK_TURQUOISE = "dark turquoise"
    DARK_VIOLET = "dark violet"
    DEEP_PINK = "deep pink"
    DEEP_SKY_BLUE = "deep sky blue"
    DIM_GRAY = "dim gray"
    DODGER_BLUE = "dodger blue"
    FIREBRICK = "firebrick"
    FLORAL_WHITE = "floral white"
    FOREST_GREEN = "forest green"
    FUCHSIA = "fuchsia"
    GAINSBORO = "gainsboro"
    GHOST_WHITE = "ghost white"
    GOLD = "gold"
    GOLDENROD = "goldenrod"
    GRAY = "gray"
    GREEN = "green"
    GREEN_YELLOW = "green yellow"
    HONEYDEW = "honeydew"
    HOT_PINK = "hot pink"
    INDIAN_RED = "indian red"
    INDIGO = "indigo"
    IVORY = "ivory"
    KHAKI = "khaki"
    LAVENDER = "lavender"
    LAVENDER_BLUSH = "lavender blush"
    LAWN_GREEN = "lawn green"
    LEMON_CHIFFON = "lemon chiffon"
    LIGHT_BLUE = "light blue"
    LIGHT_CORAL = "light coral"
    LIGHT_CYAN = "light cyan"
    LIGHT_GOLDENROD_YELLOW = "light goldenrod yellow"
    LIGHT_GRAY = "light gray"
    LIGHT_GREEN = "light green"
    LIGHT_PINK = "light pink"
    LIGHT_SALMON = "light salmon"
    LIGHT_SEA_GREEN = "light sea green"
    LIGHT_SKY_BLUE = "light sky blue"
    LIGHT_SLATE_GRAY = "light slate gray"
    LIGHT_STEEL_BLUE = "light steel blue"
    LIGHT_YELLOW = "light yellow"
    LIME = "lime"
    LIME_GREEN = "lime green"
    LINEN = "linen"
    MAGENTA = "magenta"
    MAROON = "maroon"
    MEDIUM_AQUAMARINE = "medium aquamarine"
    MEDIUM_BLUE = "medium blue"
    MEDIUM_ORCHID = "medium orchid"
    MEDIUM_PURPLE = "medium purple"
    MEDIUM_SEA_GREEN = "medium sea green"
    MEDIUM_SLATE_BLUE = "medium slate blue"
    MEDIUM_SPRING_GREEN = "medium spring green"
    MEDIUM_TURQUOISE = "medium turquoise"
    MEDIUM_VIOLET_RED = "medium violet red"
    MIDNIGHT_BLUE = "midnight blue"
    MINT_CREAM = "mint cream"
    MISTY_ROSE = "misty rose"
    MOCCASIN = "moccasin"
    NAVAJO_WHITE = "navajo white"
    NAVY = "navy"
    OLD_LACE = "old lace"
    OLIVE = "olive"
    RED = "red"
    ORANGE = "orange"
    ORANGE_RED = "orange red"
